#' 执行微生物群落样本级富集分析 (Sample-Level Enrichment Analysis)
#'
#' 该函数接受 phyloseq 对象，针对特定的目标微生物，分析样本元数据特征是否在
#' 该微生物高丰度或低丰度的样本中富集。
#'
#' @param ps A `phyloseq` object.
#' @param target_taxon A character string. The target taxon name (e.g., "Escherichia").
#' @param tax_rank A character string. The rank of the target taxon (e.g., "Genus").
#' @param sample_feat A character string. The metadata column name to group samples (e.g., "Group").
#' @param nperm Integer. Number of permutations for fgsea. Default is 1000.
#' @param min_size Integer. Minimum size of a feature set. Default is 5.
#' @param max_size Integer. Maximum size of a feature set. Default is 500.
#'
#' @return A `data.frame` (tbl_df) containing the GSEA results.
#' Columns include: pathway, pval, padj, NES, size, leadingEdge.
#'
#' @importFrom phyloseq tax_table otu_table sample_names rank_names sample_data taxa_are_rows
#' @importFrom fgsea fgsea
#' @importFrom dplyr arrange desc select
#' @importFrom tibble as_tibble
#' @importFrom DOSE gseaResult
#' @importFrom enrichplot gseaplot2
#' @importFrom methods new
#'
#' @examples
#' \dontrun{
#' # Suppose there is a ps object.
#' res <- run_microbiome_gsea(
#'     ps = ps_test_data,
#'     target_taxon = "Genus1",
#'     tax_rank = "Genus",
#'     sample_feat = c("Group", "Source")
#' )
#' print(res)
#' }
#' @export
run_microbiome_gsea <- function(ps, target_taxon, tax_rank, sample_feat, 
                                nperm = 1000, min_size = 5, max_size = 500) {
  
  # 1. 获取排序后的丰度向量 (Stats)
  # 这一步包含了 Z-score 标准化
  message(paste("Calculating ranked abundance for:", target_taxon, "..."))
  sample_ranks <- get_sorted_abundance_vector(ps, target_taxon, tax_rank)
  
  # 2. 获取样本特征集合 (Sets)
  message(paste("Generating sample sets for feature:", sample_feat, "..."))
  sample_sets <- get_sample_feature_sets(ps, sample_feat)
  
  # 检查是否有足够的集合进行分析
  if (length(sample_sets) == 0) {
    stop("No valid sample sets generated. Check your metadata column or min_size.")
  }
  
  # 3. 运行 fgsea
  message("Running GSEA analysis...")
  
  # 设置随机种子以保证结果可重复
  set.seed(123)
  
  gsea_res <- fgsea::fgsea(
    pathways = sample_sets,
    stats    = sample_ranks,
    minSize  = min_size,
    maxSize  = max_size
  )
  
  # 4. 结果整理
  # 转换为 tibble 并按 NES (Normalized Enrichment Score) 绝对值或数值排序
  # 这里按 NES 降序排列 (正富集在前，负富集在后)
  gsea_res <- gsea_res %>% 
      dplyr::arrange(dplyr::desc(NES)) %>% 
      tibble::as_tibble()
  
  # 5. 添加属性以便后续绘图
  attr(gsea_res, "sampleSets") <- sample_sets
  attr(gsea_res, "sampleRanks") <- sample_ranks
  
  return(gsea_res)
}


#' Plot GSEA Enrichment Score
#'
#' This function plots the GSEA enrichment score curve for a specific sample set (pathway)
#' using the results from `run_microbiome_gsea`.
#'
#' @param gsea_res A result object from `run_microbiome_gsea`. It should be a
#'   data frame with "sampleSets" and "sampleRanks" attributes.
#' @param set_name A character string. The name of the set (pathway) to plot.
#'
#' @return A ggplot object (generated by `fgsea::plotEnrichment`).
#'
#' @importFrom fgsea plotEnrichment
#' @importFrom ggplot2 labs
#' @export
gsea_plot = function(gsea_res, set_name){
  sample_sets = attr(gsea_res, "sampleSets")
  sample_ranks = attr(gsea_res, "sampleRanks")
  
  p_val <- gsea_res$padj[gsea_res$pathway == set_name]
  p_val_fmt <- format(p_val, scientific = TRUE, digits = 3)
  
  lab = paste0(set_name, " (p.adj = ", p_val_fmt, ")")
  
  fgsea::plotEnrichment(sample_sets[[set_name]], sample_ranks) +
    ggplot2::labs(subtitle = lab)
}

#' Convert GSEA result to gseaResult object
#' 
#' Convert the data frame returned by `run_microbiome_gsea` to a `gseaResult` object
#' for visualization with `enrichplot`.
#' 
#' @param gsea_df The data frame returned by `run_microbiome_gsea`.
#' 
#' @return A `gseaResult` object.
#' @export
as_gseaResult <- function(gsea_df) {
    if (!inherits(gsea_df, "data.frame")) {
        stop("Input must be a data frame.")
    }
    
    geneSets <- attr(gsea_df, "sampleSets")
    geneList <- attr(gsea_df, "sampleRanks")
    
    if (is.null(geneSets) || is.null(geneList)) {
        stop("Input data frame is missing 'geneSets' or 'geneList' attributes.")
    }
    
  gsea_df$Description = ""
    # Construct gseaResult object manually
    # This structure mimics the object returned by DOSE/clusterProfiler
    res <- methods::new("gseaResult",
               result     = gsea_df,
               geneSets   = geneSets,
               geneList   = geneList,
               params     = list(pvalueCutoff = 1, # Placeholder
                                 nPerm = 1000,     # Placeholder
                                 minGSSize = 5,    # Placeholder
                                 maxGSSize = 500,  # Placeholder
                                 exponent = 1),
               readable   = FALSE
    )
    
    return(res)
}

#' Visualize GSEA results using enrichplot
#' 
#' This function converts the GSEA result to a `gseaResult` object and plots it
#' using `enrichplot::gseaplot2`.
#' 
#' @param gsea_res The result from `run_microbiome_gsea`.
#' @param geneSetID The ID of the gene set (pathway) to plot. Can be numeric (index) or character (name).
#' @param title Plot title.
#' @param ... Additional arguments passed to `enrichplot::gseaplot2`.
#' 
#' @return A ggplot object.
#' @export
plot_gsea <- function(gsea_res, geneSetID, title = "", ...) {
    # Convert to gseaResult object
    gsea_obj <- as_gseaResult(gsea_res)
    
    # Plot
    p <- enrichplot::gseaplot2(gsea_obj, geneSetID = geneSetID, title = title, ...)
    
    return(p)
}
